name: Build

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        path: kdu
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Build solution
      run: msbuild kdu/Source/kdu.sln /p:Configuration=Release /p:Platform=x64 /verbosity:normal
      working-directory: ${{ github.workspace }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v5
      with:
        name: kdu-release-x64
        path: |
          kdu/**/bin/x64/Release/**/*.exe
          kdu/**/bin/x64/Release/**/*.dll
          kdu/**/bin/x64/Release/**/*.pdb
        if-no-files-found: warn
